version: '3.8'

x-default-networks: &default-networks
    - finance

services:
    finance-mongodb:
        container_name: finance-mongodb
        image: mongo:7.0.6
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        ports:
            - "37017:27017"
        volumes:
            - mongo-data:/data/db
#        networks: *default-networks

    finance-backend-app:
        container_name: finance-backend
        image: finance-backend:dev
        build:
            target: development
            context: .
            dockerfile: ./docker/Dockerfile
        volumes:
            - ${PWD}:/var/www
        ports:
            - 3000:3000
        depends_on:
            - finance-mongodb
        env_file:
            - .env
        environment:
            - VIRTUAL_HOST=finance-backend.local
            - VIRTUAL_PORT=3000
#        networks:
#            finance:
#                aliases:
#                    - finance-backend.local

volumes:
    mongo-data:  # Named volume for persistent MongoDB data

networks:
    finance:
        external: true
