version: '3.8'

x-default-networks: &default-networks
    - finance

services:
#    finance-db:
#        image: mysql:5.7
#        container_name: finance-db
#        restart: always
#        environment:
#            MYSQL_ROOT_PASSWORD: root
#            MYSQL_DATABASE: fintech
#            MYSQL_USER: admin
#            MYSQL_PASSWORD: admin
#        ports:
#            - "33060:3306"
#        volumes:
#            - mysql-data:/var/lib/mysql
#            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
#        networks: *default-networks

    finance-mongodb:
        container_name: finance-mongodb
        image: mongo:7.0.6
        restart: always
        command: [--auth]
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: fintech
        ports:
            - "37017:27017"
        volumes:
            - mongo-data:/data/db

    finance-backend-app:
        container_name: finance-backend
        image: finance-backend:dev
        build:
            target: development
            context: .
            dockerfile: ./docker/Dockerfile
        volumes:
            - ${PWD}:/var/www
        ports:
            - 3000:3000
        depends_on:
            - finance-mongodb
        env_file:
            - .env
        environment:
            - VIRTUAL_HOST=api.finance.local
            - VIRTUAL_PORT=3000

volumes:
    mongo-data:  # Named volume for persistent MongoDB data
    mysql-data:  # Named volume for persistent MySQL data

networks:
    finance:
        external: true
